name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Please:
        - Search existing issues to avoid duplicates
        - Use the latest version of ai-sdk-rust
        - Provide a minimal reproduction

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Create a new project with `cargo new test-project`
        2. Add ai-sdk dependencies
        3. Run code example
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include error messages and logs
      render: shell
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please run `rustc -vV` and paste the output
      render: shell
      placeholder: |
        rustc 1.75.0 (82e1608df 2023-12-21)
        binary: rustc
        commit-hash: 82e1608dfa6e0b5569232559e3d385fea5a93112
        commit-date: 2023-12-21
        host: x86_64-unknown-linux-gnu
        release: 1.75.0
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Crate Version
      description: Which version are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      multiple: false
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help
      placeholder: Screenshots, related issues, attempted solutions, etc.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I am using the latest version
          required: true
        - label: I have provided all required information
          required: true
